### PR TITLE
Description of Construction Helper Job

### PR DESCRIPTION
**Pull request by Remy-Reveltek**
Saving it here for future reference. Please review it so I can post it on Group.

### CODE REVIEW

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Edit line 32

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Edit line 33

**Comment by Remy-Reveltek** [comment]
Can you give me more context for it? Should I delete it or something else?

**Comment by SuzyQuant** [comment]
Rephrase, **Who are we a good fit for?**

**Comment by Remy-Reveltek** [comment]
Got you and here is the rephrased version "Our Ideal Candidate."

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Community-oriented must be what you meant for line 34

**Review by SuzyQuant — APPROVED** [review]

**Pull request merged**
