### PR TITLE
Our Team

### PR DESCRIPTION
**Pull request by Aini-Bashir**

### CODE REVIEW

**Review by bjornmage — CHANGES_REQUESTED** [review]
@Remy-Reveltek train the team to understand Creative Commons licenses better.  We cannot use this because it isn't available commercially.
The photo also doesn't reflect the tone we want for this company.
Try again with a healthier image.

**Review by Remy-Reveltek — APPROVED** [review]

**Comment by Remy-Reveltek** [comment]
Ok

**Comment by Aini-Bashir** [comment]
Can I close this PR instead of changing it as this image isn't available commercially and is not good for website?

**Comment by Remy-Reveltek** [comment]
I have closed it, do a new PR, and update the image with a Creative Commons license.

**Comment by Aini-Bashir** [comment]
Yeah, okay.

**Pull request closed without merging**
