### PR TITLE
I have worked on it#128

### LINKED ISSUE #128: Rearrange #SILKLIFE Images
image

image

- The images are not properly placed in their respective sections. These images should be tagged in the right section like Yoga, Arts, Cafe, Home, and Tech.
- When hovering over the images, no appropriate text is shown, making it difficult for the user to understand the context of the image.

Ensures the images are properly placed within their respective sections and that an appropriate text is shown on hover. This will improve the user experience and make it easier for users to navigate through the content.

### PR DESCRIPTION
**Pull request by Aleem-Reveltek**
I did Rearrange the pictures and I write the description and now if we hover on it so description will appear.

### CODE REVIEW

**Review by Remy-Reveltek — DISMISSED** [review]
A sentence should always start with a capital letter. Your all descriptions are starting form small letter.

**Comment by Aleem-Reveltek** [comment]
@Remy-Reveltek No, it is starting from capital letter.

**Review by Remy-Reveltek — CHANGES_REQUESTED** [review]
Instead of writing the definition of each category - Yoga, Arts, Cafe, Home, and Tech - describe what we do inside each of them to explain what makes each of these things a part of SILK Life.

**Comment by Aleem-Reveltek** [comment]
Okay, I'll write what we need in each category - Yoga, Arts, Cafe, Home, and Tech.

**Comment by Remy-Reveltek** [comment]
@Aleem-Reveltek, please fill out the fields of this PR and ensure proper labeling and attach it to the milestone. Also, link your PR with the issue.
See the example:
image

**Pull request merged**
