### PR TITLE
Turned Footer SVG Logo White

### LINKED ISSUE #146: Turn Footer Logo White
- Turn the footer logo "SILK CORP" white 
image

### PR DESCRIPTION
**Pull request by Remy-Reveltek**

### CODE REVIEW

**Comment by bjornmage** [comment]
We never asked for our existing logo to be deleted.  As you know, we never delete data in our organization as this is a violent way to get the end goal.
Come up with a non-destructive solution that retains our original logo.
Best option is to create a 2nd logo or styling to manipulate the current for the color you intend.

**Comment by Remy-Reveltek** [comment]
Ok, I will research it and will do it according to the requirements.

**Comment by Remy-Reveltek** [comment]
I will follow these steps to avoid a non-destructive change to the original logo stored inside our Repo.
- Open the GitHub website repo on VS Code Insider.
- Navigate to the directory where the logo file is stored.
- Create a copy of the existing logo file by right-clicking on it and selecting "Duplicate" or "Copy".
- Rename the duplicated file to "logo-white" to differentiate it from the original.
- Open the newly renamed file in a VS Code Insider.
- Modify the colors of the duplicated logo file to create the desired white version.
- Save the changes to the newly created file.
- Use Live Share to see changes.
- Commit the changes to the repo using Git.
- Push the changes to the remote GitHub repo.

**Comment by Remy-Reveltek** [comment]
I am closing this PR, as I raised a new PR #153 for this.

**Pull request closed without merging**
