### PR TITLE
create an .md file under issue #158

### LINKED ISSUE #158: Identify the Specific Services
Identify the specific services SILK will offer within the YACHT model. As per the SILK franchise model, evenly distribute services across Yoga, Arts, Cafe, Home, and Tech, with each category comprising 20% of the overall offering.

### PR DESCRIPTION
**Pull request by Aiko-Kawamura**

### CODE REVIEW

**Review by Remy-Reveltek — CHANGES_REQUESTED** [review]
You are providing general statements about all the categories we have. Can you please make bullet points for each service we are offering in each category? Creating bullet points for each service we offer in each category will make it easier to understand what specific services we provide.

**Comment by Aini-Bashir** [comment]
The .md file you provided yesterday in the chat, has great services in it. Maybe you should consider some of those for YACHT. [SILK-Corp-guide](https://github.com/NoteHive/Silk-Corp-Guide/blob/gh-pages/research/TableOfContents.md)

**Comment by Aiko-Kawamura** [comment]
@Remy-Reveltek Okay, I will edit my pr and will make bullets for each services.

@Aini-Bashir Yes, I incorporate those point from the Silk Corp Guide, will edit it to make more specific.

**Comment by Aiko-Kawamura** [comment]
I had made changes on this PR.

**Review by Remy-Reveltek — CHANGES_REQUESTED** [review]
SILK Tech provides expert assistance in selecting optimal cloud services and operating systems to align with varying business needs.
Selecting tools and applications.
Offers top-tier incubation services that facilitate business growth and development.

**Review by Remy-Reveltek — CHANGES_REQUESTED** [review]
Put all the services in the table, to make table use the following code:

# How to make table in markdown

## **Code:**

`| Column 1 Header | Column 2 Header | Column 3 Header |

|-----------------|-----------------|-----------------|

| Row 1, Column 1 | Row 1, Column 2 | Row 1, Column 3 |

| Row 2, Column 1 | Row 2, Column 2 | Row 2, Column 3 |

| Row 3, Column 1 | Row 3, Column 2 | Row 3, Column 3 |`

## **How it will look:**


| Column 1 Header | Column 2 Header | Column 3 Header |
|-----------------|-----------------|-----------------|
| Row 1, Column 1 | Row 1, Column 2 | Row 1, Column 3 |
| Row 2, Column 1 | Row 2, Column 2 | Row 2, Column 3 |
| Row 3, Column 1 | Row 3, Column 2 | Row 3, Column 3 |

**Review by Remy-Reveltek — APPROVED** [review]

**Review by duafatimaa — COMMENTED** [review]
Approve.

**Pull request merged**
