### PR TITLE
Feedback slider image

### PR DESCRIPTION
**Pull request by Aini-Bashir**

### CODE REVIEW

**Comment by Aini-Bashir** [comment]
Old image:
image

New image:
image

I updated this image besides the feedback slider.

**Review by Remy-Reveltek — APPROVED** [review]

**Comment by Aini-Bashir** [comment]
Old pic
image

New pic 
image

I have updated the image of "Sarah Devis" besides the feedback area.

**Comment by bjornmage** [comment]
These do not reflect our branding. We are not interested in this tone or mood for the website.

**Comment by Remy-Reveltek** [comment]
@Aini-Bashir, you can change the image without closing it.

**Comment by Remy-Reveltek** [comment]
@Aini-Bashir, let me know if you want assist on it.

**Comment by Aini-Bashir** [comment]
@Remy-Reveltek, I'm writing my STAR right now. I will add you to a call then.

**Pull request closed without merging**
