### PR TITLE
Content Updated #107

### PR DESCRIPTION
**Pull request by Remy-Reveltek**
Changed the Crispy logo with SILK Logo and also updated the bottom of the website.

### CODE REVIEW

**Review by bjornmage — CHANGES_REQUESTED** [review]
Did you confirm the logo actually showed up in Live Preview and looks fine once you made this change?

Also, change the "Developed By" to SILK Corp instead of WE.

**Comment by Remy-Reveltek** [comment]
I have used the same logo that is in the header.

Before
image

After
image

**Comment by Remy-Reveltek** [comment]
I am going to change the "Developed By" to SILK Corp instead of WE.

**Comment by bjornmage** [comment]
Change SILKCorp in Footer to SILK Corp

**Pull request merged**
